services:
  chatwoot:
    command: >
      sh -c "bundle exec rails db:chatwoot_prepare
      && bundle exec rails s -p 3000 -b 0.0.0.0
      && bundle exec rails db:migrate"
    environment:
      INSTALLATION_NAME: "OndaIA"
      ENABLE_ACCOUNT_SIGNUP: "false"
      INSTALLATION_ENV: "docker"
      FORCE_SSL: "false"
      DEFAULT_LOCALE: "pt_BR"
      SECRET_KEY_BASE: "1QASDfPk3G23qQYLuXGcntzQjoX54wJD"
      FRONTEND_URL: "https://chatwoot.escamax1.automacao360.com"
      NODE_ENV: "production"
      RAILS_ENV: "production"
      POSTGRES_HOST: "postgres"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_DATABASE: "chatwoot"
      POSTGRES_PASSWORD: "F5B96136BEDA62ED8DE37D2C5F628"
      REDIS_URL: "redis://redis:6379"
    image: sendingtk/chatwoot:v3.14.2
    entrypoint: docker/entrypoints/rails.sh
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot.service=chatwoot
        - traefik.http.routers.chatwoot.rule=Host(`chatwoot.escamax1.automacao360.com`)
        - traefik.http.services.chatwoot.loadbalancer.server.port=3000
        - traefik.http.routers.chatwoot.entrypoints=websecure
        - traefik.http.routers.chatwoot.tls.certresolver=le
        - traefik.http.services.chatwoot.loadbalancer.passhostheader=true
    volumes:
      - chatwoot_data:/app/storage
    networks:
      - traefik
      - interna

  chatwoot_worker:
    environment:
      INSTALLATION_NAME: "OndaIA"
      ENABLE_ACCOUNT_SIGNUP: "false"
      INSTALLATION_ENV: "docker"
      FORCE_SSL: "false"
      DEFAULT_LOCALE: "pt_BR"
      SECRET_KEY_BASE: "1QASDfPk3G23qQYLuXGcntzQjoX54wJD"
      FRONTEND_URL: "https://chatwoot.escamax1.automacao360.com"
      NODE_ENV: "production"
      RAILS_ENV: "production"
      POSTGRES_HOST: "postgres"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_DATABASE: "chatwoot"
      POSTGRES_PASSWORD: "F5B96136BEDA62ED8DE37D2C5F628"
      REDIS_URL: "redis://redis:6379"
    image: sendingtk/chatwoot:v3.14.2
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - chatwoot_data:/app/storage
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - interna

volumes:
  chatwoot_data:

networks:
  traefik:
    external: true
    name: externa
  interna:
    external: true
    name: interna